"""
constants.py — structural facts about the 2026 FIFA World Cup that never change.

This is the single source of truth for:
  * the 48 teams and their 12 groups (A-L)                       -> GROUPS
  * the three host nations (group-stage home advantage)          -> HOSTS
  * the six fixtures inside each group                           -> GROUP_FIXTURES
  * the Elo K-factor schedule by competition tier                -> k_factor()
  * FIFA's official 495-row "best eight third-placed teams" table -> THIRD_PLACE_TABLE
  * the knockout bracket wiring (R32 -> Final)                   -> LATER / ROUND_OF
  * Transfermarkt -> dataset country-name fixes                  -> TM_MAP

Team spellings match the martj42/international_results dataset exactly so the
2026 squads join cleanly onto ~150 years of historical results.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Groups, hosts, teams
# ---------------------------------------------------------------------------
GROUPS: dict[str, list[str]] = {
    "A": ["Mexico", "South Africa", "South Korea", "Czech Republic"],
    "B": ["Canada", "Bosnia and Herzegovina", "Qatar", "Switzerland"],
    "C": ["Brazil", "Morocco", "Haiti", "Scotland"],
    "D": ["United States", "Paraguay", "Australia", "Turkey"],
    "E": ["Germany", "Curaçao", "Ivory Coast", "Ecuador"],
    "F": ["Netherlands", "Japan", "Sweden", "Tunisia"],
    "G": ["Belgium", "Egypt", "Iran", "New Zealand"],
    "H": ["Spain", "Cape Verde", "Saudi Arabia", "Uruguay"],
    "I": ["France", "Senegal", "Iraq", "Norway"],
    "J": ["Argentina", "Algeria", "Austria", "Jordan"],
    "K": ["Portugal", "DR Congo", "Uzbekistan", "Colombia"],
    "L": ["England", "Croatia", "Ghana", "Panama"],
}

HOSTS: set[str] = {"United States", "Canada", "Mexico"}

# Flattened list of all 48 teams in group order. Imported widely as the
# canonical index ordering for the Monte-Carlo arrays.
ALL_TEAMS: list[str] = [t for g in GROUPS.values() for t in g]

# Tournament constants.
N_GROUP_TEAMS = 4
DATE_FORMAT = "%Y-%m-%d"
TOURNAMENT_START = "2026-06-11"   # used to stamp entered results onto the timeline
FINAL_DATE = "2026-07-19"

# The six round-robin fixtures within a 4-team group, as index pairs into the
# group's team list (matches the real 2026 group schedule order).
GROUP_FIXTURES: list[tuple[int, int]] = [(0, 1), (2, 3), (0, 2), (1, 3), (0, 3), (1, 2)]


# ---------------------------------------------------------------------------
# Elo K-factor schedule (World Football Elo conventions)
# ---------------------------------------------------------------------------
def k_factor(tournament: str) -> int:
    """Return the Elo K-factor for a match of the given competition tier.

    World Cup matches carry the heaviest weight (60), so entered 2026 results
    move ratings the most — which is exactly how later-round predictions sharpen.
    """
    t = str(tournament)
    if t == "FIFA World Cup":
        return 60
    if t in ("UEFA Euro", "Copa América", "African Cup of Nations",
             "AFC Asian Cup", "Gold Cup", "Confederations Cup"):
        return 50
    if ("qualification" in t) or (t == "UEFA Nations League"):
        return 40
    if t == "Friendly":
        return 20
    return 30


# ---------------------------------------------------------------------------
# Knockout bracket wiring (Wikipedia match numbers 73-104)
# ---------------------------------------------------------------------------
# Round-of-16 and later: winner-of-match N is decided by the winners of these
# two feeder matches. (R32 pairs are built at runtime in tournament.py because
# they depend on the realised group winners/runners-up/thirds.)
LATER: dict[int, tuple[int, int]] = {
    89: (74, 77), 90: (73, 75), 91: (76, 78), 92: (79, 80),
    93: (83, 84), 94: (81, 82), 95: (86, 88), 96: (85, 87),
    97: (89, 90), 98: (93, 94), 99: (91, 92), 100: (95, 96),
    101: (97, 98), 102: (99, 100), 104: (101, 102),
}

# Match number -> round label.
ROUND_OF: dict[int, str] = {
    **{m: "R32" for m in range(73, 89)},
    **{m: "R16" for m in range(89, 97)},
    **{m: "QF" for m in range(97, 101)},
    101: "SF", 102: "SF", 104: "Final",
}

# Order in which knockout matches are resolved (feeders before consumers).
KO_MATCH_ORDER: list[int] = (
    list(range(73, 89)) + [89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 104]
)


# ---------------------------------------------------------------------------
# Transfermarkt country-name fixes (squad-value hybrid)
# ---------------------------------------------------------------------------
TM_MAP: dict[str, str] = {
    "Korea, South": "South Korea",
    "Bosnia-Herzegovina": "Bosnia and Herzegovina",
    "Curacao": "Curaçao",
    "Cote d'Ivoire": "Ivory Coast",
}


# ---------------------------------------------------------------------------
# FIFA official best-third-placed allocation table (495 rows)
# ---------------------------------------------------------------------------
# Top two of each group plus the eight best third-placed teams reach the R32.
# *Which* R32 slot each qualifying third takes depends on which eight groups
# they come from — FIFA publishes a row for every C(12,8)=495 combination.
# Each line: <8 qualifying group letters> <8 assignments in WINNER_SLOT_ORDER>.
WINNER_SLOT_ORDER: list[str] = ["A", "B", "D", "E", "G", "I", "K", "L"]

THIRD_PLACE_TABLE_RAW = """
EFGHIJKL EJIFHGLK
DFGHIJKL HGIDJFLK
DEGHIJKL EJIDHGLK
DEFHIJKL EJIDHFLK
DEFGIJKL EGIDJFLK
DEFGHJKL EGJDHFLK
DEFGHIKL EGIDHFLK
DEFGHIJL EGJDHFLI
DEFGHIJK EGJDHFIK
CFGHIJKL HGICJFLK
CEGHIJKL EJICHGLK
CEFHIJKL EJICHFLK
CEFGIJKL EGICJFLK
CEFGHJKL EGJCHFLK
CEFGHIKL EGICHFLK
CEFGHIJL EGJCHFLI
CEFGHIJK EGJCHFIK
CDGHIJKL HGICJDLK
CDFHIJKL CJIDHFLK
CDFGIJKL CGIDJFLK
CDFGHJKL CGJDHFLK
CDFGHIKL CGIDHFLK
CDFGHIJL CGJDHFLI
CDFGHIJK CGJDHFIK
CDEHIJKL EJICHDLK
CDEGIJKL EGICJDLK
CDEGHJKL EGJCHDLK
CDEGHIKL EGICHDLK
CDEGHIJL EGJCHDLI
CDEGHIJK EGJCHDIK
CDEFIJKL CJEDIFLK
CDEFHJKL CJEDHFLK
CDEFHIKL CEIDHFLK
CDEFHIJL CJEDHFLI
CDEFHIJK CJEDHFIK
CDEFGJKL CGEDJFLK
CDEFGIKL CGEDIFLK
CDEFGIJL CGEDJFLI
CDEFGIJK CGEDJFIK
CDEFGHKL CGEDHFLK
CDEFGHJL CGJDHFLE
CDEFGHJK CGJDHFEK
CDEFGHIL CGEDHFLI
CDEFGHIK CGEDHFIK
CDEFGHIJ CGJDHFEI
BFGHIJKL HJBFIGLK
BEGHIJKL EJIBHGLK
BEFHIJKL EJBFIHLK
BEFGIJKL EJBFIGLK
BEFGHJKL EJBFHGLK
BEFGHIKL EGBFIHLK
BEFGHIJL EJBFHGLI
BEFGHIJK EJBFHGIK
BDGHIJKL HJBDIGLK
BDFHIJKL HJBDIFLK
BDFGIJKL IGBDJFLK
BDFGHJKL HGBDJFLK
BDFGHIKL HGBDIFLK
BDFGHIJL HGBDJFLI
BDFGHIJK HGBDJFIK
BDEHIJKL EJBDIHLK
BDEGIJKL EJBDIGLK
BDEGHJKL EJBDHGLK
BDEGHIKL EGBDIHLK
BDEGHIJL EJBDHGLI
BDEGHIJK EJBDHGIK
BDEFIJKL EJBDIFLK
BDEFHJKL EJBDHFLK
BDEFHIKL EIBDHFLK
BDEFHIJL EJBDHFLI
BDEFHIJK EJBDHFIK
BDEFGJKL EGBDJFLK
BDEFGIKL EGBDIFLK
BDEFGIJL EGBDJFLI
BDEFGIJK EGBDJFIK
BDEFGHKL EGBDHFLK
BDEFGHJL HGBDJFLE
BDEFGHJK HGBDJFEK
BDEFGHIL EGBDHFLI
BDEFGHIK EGBDHFIK
BDEFGHIJ HGBDJFEI
BCGHIJKL HJBCIGLK
BCFHIJKL HJBCIFLK
BCFGIJKL IGBCJFLK
BCFGHJKL HGBCJFLK
BCFGHIKL HGBCIFLK
BCFGHIJL HGBCJFLI
BCFGHIJK HGBCJFIK
BCEHIJKL EJBCIHLK
BCEGIJKL EJBCIGLK
BCEGHJKL EJBCHGLK
BCEGHIKL EGBCIHLK
BCEGHIJL EJBCHGLI
BCEGHIJK EJBCHGIK
BCEFIJKL EJBCIFLK
BCEFHJKL EJBCHFLK
BCEFHIKL EIBCHFLK
BCEFHIJL EJBCHFLI
BCEFHIJK EJBCHFIK
BCEFGJKL EGBCJFLK
BCEFGIKL EGBCIFLK
BCEFGIJL EGBCJFLI
BCEFGIJK EGBCJFIK
BCEFGHKL EGBCHFLK
BCEFGHJL HGBCJFLE
BCEFGHJK HGBCJFEK
BCEFGHIL EGBCHFLI
BCEFGHIK EGBCHFIK
BCEFGHIJ HGBCJFEI
BCDHIJKL HJBCIDLK
BCDGIJKL IGBCJDLK
BCDGHJKL HGBCJDLK
BCDGHIKL HGBCIDLK
BCDGHIJL HGBCJDLI
BCDGHIJK HGBCJDIK
BCDFIJKL CJBDIFLK
BCDFHJKL CJBDHFLK
BCDFHIKL CIBDHFLK
BCDFHIJL CJBDHFLI
BCDFHIJK CJBDHFIK
BCDFGJKL CGBDJFLK
BCDFGIKL CGBDIFLK
BCDFGIJL CGBDJFLI
BCDFGIJK CGBDJFIK
BCDFGHKL CGBDHFLK
BCDFGHJL CGBDHFLJ
BCDFGHJK HGBCJFDK
BCDFGHIL CGBDHFLI
BCDFGHIK CGBDHFIK
BCDFGHIJ HGBCJFDI
BCDEIJKL EJBCIDLK
BCDEHJKL EJBCHDLK
BCDEHIKL EIBCHDLK
BCDEHIJL EJBCHDLI
BCDEHIJK EJBCHDIK
BCDEGJKL EGBCJDLK
BCDEGIKL EGBCIDLK
BCDEGIJL EGBCJDLI
BCDEGIJK EGBCJDIK
BCDEGHKL EGBCHDLK
BCDEGHJL HGBCJDLE
BCDEGHJK HGBCJDEK
BCDEGHIL EGBCHDLI
BCDEGHIK EGBCHDIK
BCDEGHIJ HGBCJDEI
BCDEFJKL CJBDEFLK
BCDEFIKL CEBDIFLK
BCDEFIJL CJBDEFLI
BCDEFIJK CJBDEFIK
BCDEFHKL CEBDHFLK
BCDEFHJL CJBDHFLE
BCDEFHJK CJBDHFEK
BCDEFHIL CEBDHFLI
BCDEFHIK CEBDHFIK
BCDEFHIJ CJBDHFEI
BCDEFGKL CGBDEFLK
BCDEFGJL CGBDJFLE
BCDEFGJK CGBDJFEK
BCDEFGIL CGBDEFLI
BCDEFGIK CGBDEFIK
BCDEFGIJ CGBDJFEI
BCDEFGHL CGBDHFLE
BCDEFGHK CGBDHFEK
BCDEFGHJ HGBCJFDE
BCDEFGHI CGBDHFEI
AFGHIJKL HJIFAGLK
AEGHIJKL EJIAHGLK
AEFHIJKL EJIFAHLK
AEFGIJKL EJIFAGLK
AEFGHJKL EGJFAHLK
AEFGHIKL EGIFAHLK
AEFGHIJL EGJFAHLI
AEFGHIJK EGJFAHIK
ADGHIJKL HJIDAGLK
ADFHIJKL HJIDAFLK
ADFGIJKL IGJDAFLK
ADFGHJKL HGJDAFLK
ADFGHIKL HGIDAFLK
ADFGHIJL HGJDAFLI
ADFGHIJK HGJDAFIK
ADEHIJKL EJIDAHLK
ADEGIJKL EJIDAGLK
ADEGHJKL EGJDAHLK
ADEGHIKL EGIDAHLK
ADEGHIJL EGJDAHLI
ADEGHIJK EGJDAHIK
ADEFIJKL EJIDAFLK
ADEFHJKL HJEDAFLK
ADEFHIKL HEIDAFLK
ADEFHIJL HJEDAFLI
ADEFHIJK HJEDAFIK
ADEFGJKL EGJDAFLK
ADEFGIKL EGIDAFLK
ADEFGIJL EGJDAFLI
ADEFGIJK EGJDAFIK
ADEFGHKL HGEDAFLK
ADEFGHJL HGJDAFLE
ADEFGHJK HGJDAFEK
ADEFGHIL HGEDAFLI
ADEFGHIK HGEDAFIK
ADEFGHIJ HGJDAFEI
ACGHIJKL HJICAGLK
ACFHIJKL HJICAFLK
ACFGIJKL IGJCAFLK
ACFGHJKL HGJCAFLK
ACFGHIKL HGICAFLK
ACFGHIJL HGJCAFLI
ACFGHIJK HGJCAFIK
ACEHIJKL EJICAHLK
ACEGIJKL EJICAGLK
ACEGHJKL EGJCAHLK
ACEGHIKL EGICAHLK
ACEGHIJL EGJCAHLI
ACEGHIJK EGJCAHIK
ACEFIJKL EJICAFLK
ACEFHJKL HJECAFLK
ACEFHIKL HEICAFLK
ACEFHIJL HJECAFLI
ACEFHIJK HJECAFIK
ACEFGJKL EGJCAFLK
ACEFGIKL EGICAFLK
ACEFGIJL EGJCAFLI
ACEFGIJK EGJCAFIK
ACEFGHKL HGECAFLK
ACEFGHJL HGJCAFLE
ACEFGHJK HGJCAFEK
ACEFGHIL HGECAFLI
ACEFGHIK HGECAFIK
ACEFGHIJ HGJCAFEI
ACDHIJKL HJICADLK
ACDGIJKL IGJCADLK
ACDGHJKL HGJCADLK
ACDGHIKL HGICADLK
ACDGHIJL HGJCADLI
ACDGHIJK HGJCADIK
ACDFIJKL CJIDAFLK
ACDFHJKL HJFCADLK
ACDFHIKL HFICADLK
ACDFHIJL HJFCADLI
ACDFHIJK HJFCADIK
ACDFGJKL CGJDAFLK
ACDFGIKL CGIDAFLK
ACDFGIJL CGJDAFLI
ACDFGIJK CGJDAFIK
ACDFGHKL HGFCADLK
ACDFGHJL CGJDAFLH
ACDFGHJK HGJCAFDK
ACDFGHIL HGFCADLI
ACDFGHIK HGFCADIK
ACDFGHIJ HGJCAFDI
ACDEIJKL EJICADLK
ACDEHJKL HJECADLK
ACDEHIKL HEICADLK
ACDEHIJL HJECADLI
ACDEHIJK HJECADIK
ACDEGJKL EGJCADLK
ACDEGIKL EGICADLK
ACDEGIJL EGJCADLI
ACDEGIJK EGJCADIK
ACDEGHKL HGECADLK
ACDEGHJL HGJCADLE
ACDEGHJK HGJCADEK
ACDEGHIL HGECADLI
ACDEGHIK HGECADIK
ACDEGHIJ HGJCADEI
ACDEFJKL CJEDAFLK
ACDEFIKL CEIDAFLK
ACDEFIJL CJEDAFLI
ACDEFIJK CJEDAFIK
ACDEFHKL HEFCADLK
ACDEFHJL HJFCADLE
ACDEFHJK HJECAFDK
ACDEFHIL HEFCADLI
ACDEFHIK HEFCADIK
ACDEFHIJ HJECAFDI
ACDEFGKL CGEDAFLK
ACDEFGJL CGJDAFLE
ACDEFGJK CGJDAFEK
ACDEFGIL CGEDAFLI
ACDEFGIK CGEDAFIK
ACDEFGIJ CGJDAFEI
ACDEFGHL HGFCADLE
ACDEFGHK HGECAFDK
ACDEFGHJ HGJCAFDE
ACDEFGHI HGECAFDI
ABGHIJKL HJBAIGLK
ABFHIJKL HJBAIFLK
ABFGIJKL IJBFAGLK
ABFGHJKL HJBFAGLK
ABFGHIKL HGBAIFLK
ABFGHIJL HJBFAGLI
ABFGHIJK HJBFAGIK
ABEHIJKL EJBAIHLK
ABEGIJKL EJBAIGLK
ABEGHJKL EJBAHGLK
ABEGHIKL EGBAIHLK
ABEGHIJL EJBAHGLI
ABEGHIJK EJBAHGIK
ABEFIJKL EJBAIFLK
ABEFHJKL EJBFAHLK
ABEFHIKL EIBFAHLK
ABEFHIJL EJBFAHLI
ABEFHIJK EJBFAHIK
ABEFGJKL EJBFAGLK
ABEFGIKL EGBAIFLK
ABEFGIJL EJBFAGLI
ABEFGIJK EJBFAGIK
ABEFGHKL EGBFAHLK
ABEFGHJL HJBFAGLE
ABEFGHJK HJBFAGEK
ABEFGHIL EGBFAHLI
ABEFGHIK EGBFAHIK
ABEFGHIJ HJBFAGEI
ABDHIJKL IJBDAHLK
ABDGIJKL IJBDAGLK
ABDGHJKL HJBDAGLK
ABDGHIKL IGBDAHLK
ABDGHIJL HJBDAGLI
ABDGHIJK HJBDAGIK
ABDFIJKL IJBDAFLK
ABDFHJKL HJBDAFLK
ABDFHIKL HIBDAFLK
ABDFHIJL HJBDAFLI
ABDFHIJK HJBDAFIK
ABDFGJKL FJBDAGLK
ABDFGIKL IGBDAFLK
ABDFGIJL FJBDAGLI
ABDFGIJK FJBDAGIK
ABDFGHKL HGBDAFLK
ABDFGHJL HGBDAFLJ
ABDFGHJK HGBDAFJK
ABDFGHIL HGBDAFLI
ABDFGHIK HGBDAFIK
ABDFGHIJ HGBDAFIJ
ABDEIJKL EJBAIDLK
ABDEHJKL EJBDAHLK
ABDEHIKL EIBDAHLK
ABDEHIJL EJBDAHLI
ABDEHIJK EJBDAHIK
ABDEGJKL EJBDAGLK
ABDEGIKL EGBAIDLK
ABDEGIJL EJBDAGLI
ABDEGIJK EJBDAGIK
ABDEGHKL EGBDAHLK
ABDEGHJL HJBDAGLE
ABDEGHJK HJBDAGEK
ABDEGHIL EGBDAHLI
ABDEGHIK EGBDAHIK
ABDEGHIJ HJBDAGEI
ABDEFJKL EJBDAFLK
ABDEFIKL EIBDAFLK
ABDEFIJL EJBDAFLI
ABDEFIJK EJBDAFIK
ABDEFHKL HEBDAFLK
ABDEFHJL HJBDAFLE
ABDEFHJK HJBDAFEK
ABDEFHIL HEBDAFLI
ABDEFHIK HEBDAFIK
ABDEFHIJ HJBDAFEI
ABDEFGKL EGBDAFLK
ABDEFGJL EGBDAFLJ
ABDEFGJK EGBDAFJK
ABDEFGIL EGBDAFLI
ABDEFGIK EGBDAFIK
ABDEFGIJ EGBDAFIJ
ABDEFGHL HGBDAFLE
ABDEFGHK HGBDAFEK
ABDEFGHJ HGBDAFEJ
ABDEFGHI HGBDAFEI
ABCHIJKL IJBCAHLK
ABCGIJKL IJBCAGLK
ABCGHJKL HJBCAGLK
ABCGHIKL IGBCAHLK
ABCGHIJL HJBCAGLI
ABCGHIJK HJBCAGIK
ABCFIJKL IJBCAFLK
ABCFHJKL HJBCAFLK
ABCFHIKL HIBCAFLK
ABCFHIJL HJBCAFLI
ABCFHIJK HJBCAFIK
ABCFGJKL CJBFAGLK
ABCFGIKL IGBCAFLK
ABCFGIJL CJBFAGLI
ABCFGIJK CJBFAGIK
ABCFGHKL HGBCAFLK
ABCFGHJL HGBCAFLJ
ABCFGHJK HGBCAFJK
ABCFGHIL HGBCAFLI
ABCFGHIK HGBCAFIK
ABCFGHIJ HGBCAFIJ
ABCEIJKL EJBAICLK
ABCEHJKL EJBCAHLK
ABCEHIKL EIBCAHLK
ABCEHIJL EJBCAHLI
ABCEHIJK EJBCAHIK
ABCEGJKL EJBCAGLK
ABCEGIKL EGBAICLK
ABCEGIJL EJBCAGLI
ABCEGIJK EJBCAGIK
ABCEGHKL EGBCAHLK
ABCEGHJL HJBCAGLE
ABCEGHJK HJBCAGEK
ABCEGHIL EGBCAHLI
ABCEGHIK EGBCAHIK
ABCEGHIJ HJBCAGEI
ABCEFJKL EJBCAFLK
ABCEFIKL EIBCAFLK
ABCEFIJL EJBCAFLI
ABCEFIJK EJBCAFIK
ABCEFHKL HEBCAFLK
ABCEFHJL HJBCAFLE
ABCEFHJK HJBCAFEK
ABCEFHIL HEBCAFLI
ABCEFHIK HEBCAFIK
ABCEFHIJ HJBCAFEI
ABCEFGKL EGBCAFLK
ABCEFGJL EGBCAFLJ
ABCEFGJK EGBCAFJK
ABCEFGIL EGBCAFLI
ABCEFGIK EGBCAFIK
ABCEFGIJ EGBCAFIJ
ABCEFGHL HGBCAFLE
ABCEFGHK HGBCAFEK
ABCEFGHJ HGBCAFEJ
ABCEFGHI HGBCAFEI
ABCDIJKL IJBCADLK
ABCDHJKL HJBCADLK
ABCDHIKL HIBCADLK
ABCDHIJL HJBCADLI
ABCDHIJK HJBCADIK
ABCDGJKL CJBDAGLK
ABCDGIKL IGBCADLK
ABCDGIJL CJBDAGLI
ABCDGIJK CJBDAGIK
ABCDGHKL HGBCADLK
ABCDGHJL HGBCADLJ
ABCDGHJK HGBCADJK
ABCDGHIL HGBCADLI
ABCDGHIK HGBCADIK
ABCDGHIJ HGBCADIJ
ABCDFJKL CJBDAFLK
ABCDFIKL CIBDAFLK
ABCDFIJL CJBDAFLI
ABCDFIJK CJBDAFIK
ABCDFHKL HFBCADLK
ABCDFHJL CJBDAFLH
ABCDFHJK HJBCAFDK
ABCDFHIL HFBCADLI
ABCDFHIK HFBCADIK
ABCDFHIJ HJBCAFDI
ABCDFGKL CGBDAFLK
ABCDFGJL CGBDAFLJ
ABCDFGJK CGBDAFJK
ABCDFGIL CGBDAFLI
ABCDFGIK CGBDAFIK
ABCDFGIJ CGBDAFIJ
ABCDFGHL CGBDAFLH
ABCDFGHK HGBCAFDK
ABCDFGHJ HGBCAFDJ
ABCDFGHI HGBCAFDI
ABCDEJKL EJBCADLK
ABCDEIKL EIBCADLK
ABCDEIJL EJBCADLI
ABCDEIJK EJBCADIK
ABCDEHKL HEBCADLK
ABCDEHJL HJBCADLE
ABCDEHJK HJBCADEK
ABCDEHIL HEBCADLI
ABCDEHIK HEBCADIK
ABCDEHIJ HJBCADEI
ABCDEGKL EGBCADLK
ABCDEGJL EGBCADLJ
ABCDEGJK EGBCADJK
ABCDEGIL EGBCADLI
ABCDEGIK EGBCADIK
ABCDEGIJ EGBCADIJ
ABCDEGHL HGBCADLE
ABCDEGHK HGBCADEK
ABCDEGHJ HGBCADEJ
ABCDEGHI HGBCADEI
ABCDEFKL CEBDAFLK
ABCDEFJL CJBDAFLE
ABCDEFJK CJBDAFEK
ABCDEFIL CEBDAFLI
ABCDEFIK CEBDAFIK
ABCDEFIJ CJBDAFEI
ABCDEFHL HFBCADLE
ABCDEFHK HEBCAFDK
ABCDEFHJ HJBCAFDE
ABCDEFHI HEBCAFDI
ABCDEFGL CGBDAFLE
ABCDEFGK CGBDAFEK
ABCDEFGJ CGBDAFEJ
ABCDEFGI CGBDAFEI
ABCDEFGH HGBCAFDE
"""

# Parsed form: frozenset(qualifying group letters) -> {slot_letter: source_group}.
THIRD_PLACE_TABLE: dict[frozenset, dict[str, str]] = {}
for _line in THIRD_PLACE_TABLE_RAW.strip().split("\n"):
    _qual, _assign = _line.split()
    THIRD_PLACE_TABLE[frozenset(_qual)] = dict(zip(WINNER_SLOT_ORDER, list(_assign)))

assert len(THIRD_PLACE_TABLE) == 495, f"expected 495 third-place rows, got {len(THIRD_PLACE_TABLE)}"
assert len(ALL_TEAMS) == len(set(ALL_TEAMS)) == 48, "expected 48 unique teams"
